spring.cloud.stream:
  function:
    definition: dataProcessor
  bindings:
    dataProcessor-in-0:
      destination: input-topic
    dataProcessor-out-0:
      destination: enriched-topic


  kafka.streams.binder:
    brokers: localhost:19092,localhost:29092,localhost:39092
    configuration:
      num.stream.threads: 5



  management.health.binders:
      enabled: true

  server:
    port: 9000

